name: Manually triggered workflow inputs

on:
  workflow_dispatch:
    inputs:
      branch_name:
        branch: 'Branch name'
        required: false
        default: 'main'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Branch: ${{ github.event.inputs.branch_name }}!"
